assets:
  rubygems.yml: zerocracy/home#assets/rubygems.yml
  s3cfg: zerocracy/home#assets/s3cfg
install: |
  sudo gem install pdd
  sudo gem install est
release:
  script: |-
    pdd --verbose --file=/dev/null
    sudo bundle install
    rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/est/version.rb
    git add lib/est/version.rb
    git commit -m "version set to ${tag}"
    gem build est.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
    s3cmd --no-progress put assets/est.xsd --acl-public --config=../s3cfg s3://est-xsd.teamed.io/${tag}.xsd
    s3cmd --no-progress put assets/est.xsl --acl-public --config=../s3cfg s3://est-xsl.teamed.io/${tag}.xsl
    est --dir=./est --format=xml --file=est-estimate.xml
    s3cmd --no-progress put est-estimate.xml --config=../s3cfg s3://est.teamed.io/est.xml
  commanders:
  - yegor256
architect:
- yegor256
- davvd
merge:
  commanders: []
deploy: {}
